---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerSection
  labels:
    app: CustomerSection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerSection
  template:
    metadata:
      labels:
        app: CustomerSection
    spec:
      containers:
        - name: CustomerSection
          image: username/CustomerSection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderView
  labels:
    app: OrderView
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderView
  template:
    metadata:
      labels:
        app: OrderView
    spec:
      containers:
        - name: OrderView
          image: username/OrderView:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OwnerSection
  labels:
    app: OwnerSection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OwnerSection
  template:
    metadata:
      labels:
        app: OwnerSection
    spec:
      containers:
        - name: OwnerSection
          image: username/OwnerSection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderStatus
  labels:
    app: OrderStatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderStatus
  template:
    metadata:
      labels:
        app: OrderStatus
    spec:
      containers:
        - name: OrderStatus
          image: username/OrderStatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliveryList
  labels:
    app: DeliveryList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliveryList
  template:
    metadata:
      labels:
        app: DeliveryList
    spec:
      containers:
        - name: DeliveryList
          image: username/DeliveryList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliverySection
  labels:
    app: DeliverySection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliverySection
  template:
    metadata:
      labels:
        app: DeliverySection
    spec:
      containers:
        - name: DeliverySection
          image: username/DeliverySection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerNotySection
  labels:
    app: CustomerNotySection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerNotySection
  template:
    metadata:
      labels:
        app: CustomerNotySection
    spec:
      containers:
        - name: CustomerNotySection
          image: username/CustomerNotySection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerSection
  labels:
    app: CustomerSection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerSection


---


apiVersion: v1
kind: Service
metadata:
  name: OrderView
  labels:
    app: OrderView
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OrderView


---


apiVersion: v1
kind: Service
metadata:
  name: OwnerSection
  labels:
    app: OwnerSection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OwnerSection


---


apiVersion: v1
kind: Service
metadata:
  name: OrderStatus
  labels:
    app: OrderStatus
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OrderStatus


---


apiVersion: v1
kind: Service
metadata:
  name: DeliveryList
  labels:
    app: DeliveryList
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DeliveryList


---


apiVersion: v1
kind: Service
metadata:
  name: DeliverySection
  labels:
    app: DeliverySection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DeliverySection


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerNotySection
  labels:
    app: CustomerNotySection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerNotySection

