apiVersion: v1
kind: Service
metadata:
  name: CustomerNotySection
  labels:
    app: CustomerNotySection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerNotySection